---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.nameSpace }}-shared-data-vol
  labels:
    folder: root
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: {{ .Values.nameSpace }}
    name: {{ .Values.nameSpace }}-shared-data
  gcePersistentDisk:
    pdName: nfs
    fsType: ext4
# nodeAffinity is required so we use a "generic" value that all nodes share, as the EFS is already mounted there
  
