---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.nameSpace }}-shared-data-vol
  labels:
    folder: root
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: {{ .Values.nameSpace }}
    name: {{ .Values.nameSpace }}-shared-data
  storageClassName: standard
  local:
    path: /home/ec2-user/efs/data/{{ .Values.nameSpace }}
# nodeAffinity is required so we use a "generic" value that all nodes share, as the EFS is already mounted there
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/os
          operator: In
          values:
            - linux