---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.nameSpace }}-shared-data
  namespace: {{ .Values.nameSpace }}
spec:
  storageClassName: standard
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gb
  selector:
    matchLabels:
      folder: root
