---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.nameSpace }}-shared-data
  namespace: {{ .Values.nameSpace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  selector:
    matchLabels:
      folder: root
