---
{{ if empty .Values.rds }}
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
  clusterIP: None
{{ end }}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: platform
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    hazelcast: "true"
  name: platform
spec:
  ports:
    - name: "8090"
      port: 8090
      targetPort: 8090
    - name: "5005"
      port: 5005
      targetPort: 5005
    - name: "1099"
      port: 1099
      targetPort: 1099
    - name: hazelcast
      port: 5701
    - name: js-debug
      port: 9230
  selector:
    app: platform
status:
  loadBalancer: {}
