---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: http-api-worker-ingress-{{ .Values.nameSpace }}
  namespace: {{ .Values.nameSpace }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
    nginx.ingress.kubernetes.io/proxy-ssl-protocols: "TLSv1.2"
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-samesite: "None"
    nginx.ingress.kubernetes.io/session-cookie-expires: "300"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "300"
    # CORS configuration
    #nginx.ingress.kubernetes.io/enable-cors: "true"
    #nginx.ingress.kubernetes.io/cors-allow-origin: "https://*.{{ .Values.nameSpace }}.sweepr.com"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      set $cors '';
      if ($http_origin ~ '^https?:\/\/(localhost:[0-9]+|.*\.sweepr\.com$)') {
        set $cors 'true';
      }

      if ($cors = 'true') {
        add_header 'Access-Control-Allow-Origin' "$http_origin" always;
        add_header 'Access-Control-Allow-Credentials' 'true' always;
        add_header 'Access-Control-Allow-Headers' 'Authorization,Accept,Origin,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range' always;
        add_header 'Access-Control-Allow-Methods' 'GET,POST,OPTIONS,PUT,DELETE,PATCH' always;
        add_header 'Strict-Transport-Security' 	'max-age=31536000; includeSubDomains';
        add_header 'Content-Security-Policy' 'upgrade-insecure-requests';
        # Possible required to be able to read Authorization header in frontend
        #add_header 'Access-Control-Expose-Headers' 'Authorization' always;
      }
      
      if ($request_method = 'OPTIONS') {
        add_header 'Access-Control-Allow-Origin' "$http_origin" always;
        add_header 'Access-Control-Allow-Credentials' 'true' always;
        add_header 'Access-Control-Allow-Headers' 'Authorization,Accept,Origin,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range' always;
        add_header 'Access-Control-Allow-Methods' 'GET,POST,OPTIONS,PUT,DELETE,PATCH' always;
        add_header 'Strict-Transport-Security' 	'max-age=31536000; includeSubDomains';
        add_header 'Content-Security-Policy' 'upgrade-insecure-requests';
        add_header 'Access-Control-Max-Age' 1728000;
        add_header 'Content-Type' 'text/plain charset=UTF-8';
        add_header 'X-Content-Type-Options' 'nosniff';
        add_header 'Content-Length' 0;
        return 204;
      }
spec:
  tls:
    - hosts:
        -  "api.{{ .Values.hostUrl | default .Values.nameSpace }}.sweepr.com"
      secretName: {{ .Values.nameSpace }}-ingress-tls
  rules:
      - host: "api.{{ .Values.hostUrl | default .Values.nameSpace }}.sweepr.com"
        http:
          paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: platform
                  port:
                    number: 8090
